# docs/_config.yml
# Site config for GitHub Pages using the Just-the-Docs theme.

title: BitNet Hybrid Orchestrator
description: Hybrid orchestration (hierarchical + parallel + sequential) with BitNet as the core reasoner and TinyBERT guard — edge-ready.

# --- GitHub Pages / routing ---
url: "https://ShiySabiniano.github.io"
baseurl: "/bitnet-hybrid-orchestrator"   # repo name for project pages
permalink: pretty
repository: "ShiySabiniano/bitnet-hybrid-orchestrator"

# --- Theme ---
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: /assets/logo.svg
search_enabled: true
heading_anchors: true
enable_copy_code_button: true
back_to_top: true
back_to_top_text: "Back to top"

# --- Top-right links ---
aux_links:
  "GitHub Repo": "https://github.com/ShiySabiniano/bitnet-hybrid-orchestrator"
  "Open in Colab": "https://colab.research.google.com/gist/ShiySabiniano/a34e01bcfc227cddc55a6634f1823539/bitnet_tinybert_orchestrator_colab.ipynb"
aux_links_new_tab: true

# --- Footer (AGPL §13 hint: expose commit) ---
footer_content: >
  Source: <a href="https://github.com/ShiySabiniano/bitnet-hybrid-orchestrator/tree/{{ site.github.build_revision | default: 'HEAD' }}">commit</a>
  &nbsp;•&nbsp; License: <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPL-3.0-or-later</a>
  &nbsp;•&nbsp; Owner: Shiy Sabiniano

# --- Mermaid diagrams (works with Just-the-Docs on GitHub Pages) ---
mermaid:
  enabled: true

# --- Plugins allowed by GitHub Pages ---
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

# --- Exclusions (keep site lean) ---
exclude:
  - "notebooks/"
  - ".github/"
  - ".venv/"
  - "ui/__pycache__/"
  - "orchestrator/__pycache__/"

# --- Markdown / kramdown defaults ---
kramdown:
  input: GFM
  hard_wrap: false

# --- Defaults for pages (optional ordering is set via front matter on each page) ---
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
