# docs/_config.yml
# GitHub Pages config for the docs site (Just the Docs)

title: BitNet Hybrid Orchestrator
description: >
  Hybrid orchestration for edge devices: hierarchical + parallel + sequential
  with BitNet as the reasoner and TinyBERT safeguards.

# Theme
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: /assets/logo.svg
favicon_ico: /assets/logo.svg

# Site URL (helps canonical links). Replace if you fork.
url: https://ShiySabiniano.github.io
baseurl: /bitnet-hybrid-orchestrator

# Navigation & UX
permalink: pretty
search_enabled: true
heading_anchors: true
enable_copy_code_button: true
nav_external_links:
  - title: Repo
    url: https://github.com/ShiySabiniano/bitnet-hybrid-orchestrator
    hide_icon: false

# Mermaid support (for diagrams in docs)
mermaid: true

# “Edit this page” links
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/ShiySabiniano/bitnet-hybrid-orchestrator"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "edit"

# Footer links (right side, open in new tab)
aux_links:
  Colab Demo: https://colab.research.google.com/gist/ShiySabiniano/a34e01bcfc227cddc55a6634f1823539/bitnet_tinybert_orchestrator_colab.ipynb
  GitHub Repo: https://github.com/ShiySabiniano/bitnet-hybrid-orchestrator
  Security Policy: https://github.com/ShiySabiniano/bitnet-hybrid-orchestrator/blob/main/SECURITY.md
  Report Vulnerability: https://github.com/ShiySabiniano/bitnet-hybrid-orchestrator/security/advisories/new
  PGP Public Key: https://raw.githubusercontent.com/ShiySabiniano/bitnet-hybrid-orchestrator/main/security/pgp/ShiySabiniano.asc
aux_links_new_tab: true

# Footer text (left side)
footer_content: >
  © 2025 Shiy Sabiniano · Licensed AGPL-3.0-or-later ·
  For network-hosted instances, expose the running commit per AGPL §13 (see COMPLIANCE.md).

# Optional callout styles (use :::note / :::warning in pages)
callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: yellow
  danger:
    title: Important
    color: red

# Plugins allowed on GitHub Pages
plugins:
  - jekyll-seo-tag
