name: ci
on:
  push: { branches: [main] }
  pull_request: {}
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r orchestrator/requirements.txt
          pip install pytest ruff black
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Test
        run: pytest -q
